name: bottom_sheet_bar
description: A toolbar that aligns to the bottom of a widget and expands into a bottom sheet.
version: 2.3.7
homepage: https://github.com/mhrst/bottom_sheet_bar
repository: https://github.com/mhrst/bottom_sheet_bar
issue_tracker: https://github.com/mhrst/bottom_sheet_bar/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  measure_size: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1